import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, KeyRound, ShieldCheck, WifiOff } from 'lucide-react';
import { MarketingHeader, MarketingFooter } from '@/components/landing/MarketingChrome';
import StructuredData from '@/components/landing/StructuredData';
import PasswordGeneratorCard from '@/components/landing/PasswordGeneratorCard';
import { SITE_URL } from '@/lib/site';

/**
 * A free password generator, and the same rule the other free tools follow:
 * genuinely useful, no account, nothing uploaded, honestly connected to the
 * product.
 *
 * The thing worth publishing is not the generator — everyone has one — it is
 * the two mistakes almost none of them get right, both of which are invisible
 * in the output:
 *
 *   · `Math.random()` instead of a CSPRNG produces predictable strings that
 *     look exactly as random as real ones.
 *   · `random % alphabet.length` biases the first few characters of the
 *     alphabet, quietly removing bits from every password it makes.
 *
 * lib/vault/password.ts avoids both and explains why in the code. The page
 * reports real entropy for the settings on screen rather than a "strength
 * meter" that would call `Password1!` strong.
 *
 * Entirely client-side — the generator runs in the visitor's browser off the
 * operating system's random source, so nothing is transmitted. That is the
 * same reason /qr and /pdf are client-side: a QR is usually a private link, a
 * contract should not visit a conversion service, and a password should never
 * be generated by somebody else's server.
 */

const TITLE = 'Free password generator — strong passwords and passphrases, in your browser';
const DESCRIPTION =
  'Generate strong passwords and memorable passphrases with your device’s secure random source. Real entropy in bits, no modulo bias, nothing uploaded, no account. Plus an encrypted team vault your server cannot read.';

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: `${SITE_URL}/password` },
  openGraph: { title: TITLE, description: DESCRIPTION, url: `${SITE_URL}/password`, type: 'website' },
};

/** Answered on the page in the same words — an FAQPage whose questions are not visible is spam. */
const FAQ = [
  {
    q: 'Is anything sent to your server?',
    a: 'No. The generator runs entirely in your browser using crypto.getRandomValues, the operating system’s secure random source. The page makes no network request while generating, and nothing is stored unless you choose to save it in a vault.',
  },
  {
    q: 'How long should a password be?',
    a: 'Length matters more than symbols. With upper and lower case, digits and symbols, each character adds about 6.5 bits, so a 20-character password is around 130 bits — far beyond what offline cracking of a leaked hash can reach. Anything under about 60 bits is within reach of rented hardware.',
  },
  {
    q: 'Is a passphrase as strong as a password?',
    a: 'It depends entirely on the word list and the number of words, and this page shows the real figure rather than assuming. Passphrases are worth using where a human has to read one aloud or type it on a television remote — a vault passphrase is the obvious case.',
  },
  {
    q: 'What is the team vault?',
    a: 'A place in RunButter for the logins a company shares — the domain registrar, the analytics account, the social inbox. Items are encrypted in the browser with a key derived from a workspace passphrase that is never transmitted, so the database stores only ciphertext and the server cannot read any of it. There is no recovery, which is the property that makes it worth having.',
  },
  {
    q: 'Is it as secure as a dedicated password manager?',
    a: 'It is not a replacement for one: there are no per-user keys, no browser extension and no autofill. What it replaces is the shared spreadsheet, the pinned chat message and the sticky note — which is where those credentials actually live today.',
  },
];

export default function PasswordPage() {
  return (
    <>
      <StructuredData faq={FAQ} />
      <MarketingHeader />
      <main className="mx-auto max-w-3xl px-5 py-14 sm:py-20">
        <div className="inline-flex items-center gap-1.5 rounded-full bg-accent/10 text-accent px-2.5 py-1 text-2xs font-semibold">
          <KeyRound className="w-3 h-3" /> Free tool
        </div>
        <h1 className="mt-4 text-3xl sm:text-4xl font-medium tracking-tight text-primary">
          Password generator
        </h1>
        <p className="mt-3 text-md text-secondary">
          Strong passwords and memorable passphrases, generated by your own device. No account,
          no upload, and the strength figure is the real number of bits rather than a colour.
        </p>

        <div className="mt-8">
          <PasswordGeneratorCard />
        </div>

        <div className="mt-10 grid sm:grid-cols-3 gap-4">
          <Point icon={WifiOff} title="Nothing leaves the page">
            Generated with <code className="text-primary">crypto.getRandomValues</code>, your
            operating system&rsquo;s secure random source. No request is made while generating.
          </Point>
          <Point icon={ShieldCheck} title="No modulo bias">
            Most generators map a random byte with <code className="text-primary">%</code>, which
            makes the first few letters of the alphabet more likely and silently removes bits.
            This one rejects and redraws instead.
          </Point>
          <Point icon={KeyRound} title="Bits, not colours">
            The figure shown is log₂(alphabet<sup>length</sup>) for exactly the settings above — the
            true strength of a uniform draw, which is what these are.
          </Point>
        </div>

        <section className="mt-12 rounded-2xl bg-surface ring-1 ring-subtle p-6">
          <h2 className="text-md font-medium text-primary">Somewhere for your team&rsquo;s shared logins</h2>
          <p className="mt-2 text-sm text-secondary">
            Every company has a handful of accounts that belong to nobody in particular — the
            registrar, the analytics login, the shared social inbox. They end up in a spreadsheet
            because buying a fifth subscription to hold six passwords is a worse trade.
          </p>
          <p className="mt-2 text-sm text-secondary">
            RunButter has a vault beside the rest of the company&rsquo;s records. Items are encrypted
            in your browser with a key built from a workspace passphrase that is never sent
            anywhere, so the database holds ciphertext and nothing that can open it. There is no
            reset — which is the whole reason it is worth using.
          </p>
          <Link href="/auth/login"
            className="mt-4 inline-flex items-center gap-1.5 h-9 px-4 rounded-lg text-sm font-semibold text-inverse-fg bg-inverse hover:bg-inverse/90">
            Try RunButter free <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </section>

        <section className="mt-12">
          <h2 className="text-md font-medium text-primary">Questions</h2>
          <dl className="mt-4 flex flex-col gap-5">
            {FAQ.map((f) => (
              <div key={f.q}>
                <dt className="text-sm font-medium text-primary">{f.q}</dt>
                <dd className="mt-1 text-sm text-secondary">{f.a}</dd>
              </div>
            ))}
          </dl>
        </section>
      </main>
      <MarketingFooter />
    </>
  );
}

function Point({ icon: Icon, title, children }: { icon: any; title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl bg-surface ring-1 ring-subtle p-4">
      <Icon className="w-4 h-4 text-accent" />
      <h3 className="mt-2 text-sm font-medium text-primary">{title}</h3>
      <p className="mt-1 text-2xs text-secondary leading-relaxed">{children}</p>
    </div>
  );
}
