-- ============================================================================
-- RunButter — 0126_plan_limits_rest.sql
--
-- 0108 made ONE of the six plan limits real. This makes the rest real, and
-- fixes a hole in the one that already was.
--
-- ── WHAT 0108 LEFT ──────────────────────────────────────────────────────────
-- It built `plan_limits` (seeded from lib/plans.ts, guarded by `npm run
-- check:plans`), `plan_limit()`, `workspace_plan_of()` and
-- `enforce_record_limit()`, and wired the last of those into `create_record`
-- and `import_records`. That covers `maxRecords`. The table has five more
-- columns — seats, positions, candidates, automations, e-signatures per month —
-- and NOTHING read any of them. They were seeded, printed on the pricing page,
-- and enforced nowhere, which is the same state `maxRecords` was in before 0108
-- and for the same reason: the limit lived in a table nobody joined.
--
-- ── THE RECORD COUNT MISSED TWO TABLES ──────────────────────────────────────
-- `workspace_record_count` sums eleven tables and omits `pipeline_records` and
-- `orders`. Both are records a PERSON makes — a deal on the Sales board, an
-- order on the Orders screen — so a Free workspace could hold five hundred
-- records plus unlimited deals and unlimited orders, and the two screens most
-- likely to be used every day were the two that did not count. Neither
-- `create_pipeline_record` (0092) nor `save_order` (0124) enforced anything
-- either, because both are dedicated RPCs rather than branches of
-- `create_record`, which is where the guard sits.
--
-- That is the recurring shape of this bug and it is worth naming: a limit
-- enforced in ONE function is enforced only for the paths that go through it.
-- The five functions redefined below are every remaining way a person creates
-- something the price list counts.
--
-- ── FAILS OPEN, EVERYWHERE, DELIBERATELY ────────────────────────────────────
-- Unchanged from 0108 and from lib/plans-server.ts: an unreadable plan resolves
-- to unlimited, an unknown plan name resolves to unlimited, a missing limit row
-- resolves to unlimited. The cost of a miss is a free workspace keeping one
-- extra row for an hour; the cost of a false block is a paying customer unable
-- to enter data with nothing on screen explaining why. The PlanGate bug this
-- codebase already paid for once walled an Enterprise customer out of a feature
-- they owned. The two mistakes are not symmetrical and the code must not
-- pretend they are.
--
-- ── AND A WAY TO SEE IT COMING ──────────────────────────────────────────────
-- `get_plan_usage` is the other half and is not optional. A ceiling you cannot
-- see is one you discover by being refused, in the middle of doing something
-- else. It returns the SAME counts the enforcement uses — two implementations
-- of "how many records is that" eventually disagree, and being refused at 500
-- while the screen says 486 is worse than showing no number at all.
-- ============================================================================

-- ── The count, redefined IN FULL ────────────────────────────────────────────
-- Deals and orders join it. Not messages, notes, files, deliveries, run steps
-- or webhook logs: those are generated BY the product rather than entered into
-- it, and metering them would mean a workspace hits its ceiling because its own
-- automations ran. `offers` is not counted separately — an offer IS a row in
-- `invoices` with a different `kind`, the same fold `builtin_object_slug` makes.
create or replace function workspace_record_count(p_workspace uuid)
returns bigint language sql stable security definer set search_path = public as $$
  select
      (select count(*) from organizations    where workspace_id = p_workspace)
    + (select count(*) from people           where workspace_id = p_workspace)
    + (select count(*) from invoices         where workspace_id = p_workspace)
    + (select count(*) from expenses         where workspace_id = p_workspace)
    + (select count(*) from transactions     where workspace_id = p_workspace)
    + (select count(*) from products         where workspace_id = p_workspace)
    + (select count(*) from campaigns        where workspace_id = p_workspace)
    + (select count(*) from projects         where workspace_id = p_workspace)
    + (select count(*) from issues           where workspace_id = p_workspace)
    + (select count(*) from assets           where workspace_id = p_workspace)
    + (select count(*) from custom_records   where workspace_id = p_workspace)
    + (select count(*) from pipeline_records where workspace_id = p_workspace)
    + (select count(*) from orders           where workspace_id = p_workspace)
$$;

/**
 * The generic guard, beside 0108's record-specific one.
 *
 * `enforce_record_limit` stays exactly as it is — it is called from three
 * migrations and re-implementing it here would mean two answers to one
 * question. This is the same shape for the limits that count a different table,
 * and it takes the count as an ARGUMENT rather than computing it: the counts
 * differ per limit (one is a monthly window), and a function that knew how to
 * count all six would be the place every future limit gets bolted onto.
 *
 * The exception name carries the key, so a client can tell "too many
 * automations" from "too many seats" without reading English.
 */
create or replace function enforce_plan_limit(
  p_workspace uuid, p_key text, p_used bigint, p_adding int default 1
) returns void language plpgsql security definer set search_path = public as $$
declare v_plan text; v_max int;
begin
  if p_workspace is null then return; end if;
  v_plan := workspace_plan_of(p_workspace);
  v_max  := plan_limit(v_plan, p_key);
  if v_max < 0 then return; end if;

  if coalesce(p_used, 0) + greatest(coalesce(p_adding, 1), 1) > v_max then
    -- A limit of zero is a feature somebody has not bought, not an allowance
    -- they have spent, and saying "includes 0 automations and this workspace
    -- has 0" would be true and useless.
    if v_max = 0 then
      raise exception 'PLAN_LIMIT_%: the % plan does not include this. Upgrade to use it.',
        upper(p_key), v_plan;
    else
      raise exception 'PLAN_LIMIT_%: the % plan includes % and this workspace has %. Upgrade to add more.',
        upper(p_key), v_plan, v_max, p_used;
    end if;
  end if;
end $$;

/**
 * Every counter, for the screen and for the checks.
 *
 * Member-visible rather than owner-only. Knowing you are near a limit is not
 * privileged information; being surprised by one is the actual harm, and
 * owner-only would hide the number from the person who hits it.
 */
create or replace function get_plan_usage(p_privy text, p_workspace uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_plan text;
begin
  if not is_workspace_member(p_workspace, p_privy) then raise exception 'NOT_A_MEMBER'; end if;
  v_plan := workspace_plan_of(p_workspace);
  return jsonb_build_object(
    'plan', v_plan,
    'records',     workspace_record_count(p_workspace),
    -- A seat is somebody who has one OR has been sent one. Counting `accounts`
    -- alone would let a Free workspace send fifty invitations and only discover
    -- the limit as people redeemed them — refusing the fiftieth person to click
    -- a link they were legitimately sent.
    'seats',       (select count(*) from accounts where workspace_id = p_workspace)
                 + (select count(*) from company_users
                     where company_id = p_workspace and invite_token is not null and privy_user_id is null),
    'automations', (select count(*) from automations where workspace_id = p_workspace),
    -- HR is tenanted by company_id, and workspace_id = company_id (0005's sync
    -- trigger). Reading `workspaces` here would be the bug `resolveHrCompany`
    -- exists to prevent.
    'positions',   (select count(*) from positions  where company_id = p_workspace),
    'candidates',  (select count(*) from candidates where company_id = p_workspace),
    -- E-signatures are metered PER MONTH, so this is a window and not a total:
    -- the calendar month in UTC, which is what the plans screen must say out
    -- loud. A rolling window would refuse somebody on the 2nd for something
    -- they did on the 4th of last month.
    'esign_month', (select count(*) from sign_documents
                     where workspace_id = p_workspace
                       and created_at >= date_trunc('month', now() at time zone 'utc')),
    'limits', (select to_jsonb(l) - 'plan' from plan_limits l where l.plan = v_plan)
  );
end $$;

revoke all on function workspace_record_count(uuid)                      from public, anon, authenticated;
revoke all on function enforce_plan_limit(uuid, text, bigint, int)       from public, anon, authenticated;
revoke all on function get_plan_usage(text, uuid)                        from public, anon, authenticated;
grant execute on function workspace_record_count(uuid)                    to service_role;
grant execute on function enforce_plan_limit(uuid, text, bigint, int)     to service_role;
grant execute on function get_plan_usage(text, uuid)                      to service_role;

-- Every count above is `where <tenant> = ?`, so each wants an index on that
-- column. These are the ones that did not have one — without them a Free
-- workspace's create path scans them in full on every insert.
create index if not exists idx_orders_ws           on orders(workspace_id);
create index if not exists idx_custom_records_ws   on custom_records(workspace_id);
create index if not exists idx_pipeline_records_ws on pipeline_records(workspace_id);
create index if not exists idx_automations_ws      on automations(workspace_id);
create index if not exists idx_sign_documents_ws_created on sign_documents(workspace_id, created_at);

-- ============================================================================
-- The five functions that could create something nobody was counting.
-- Each is redefined IN FULL from its latest definition, per the house rule:
-- extend the newest version, never add a parallel one.
-- ============================================================================

-- ── Deals (0092), which were free ───────────────────────────────────────────
create or replace function create_pipeline_record(
  p_privy text, p_workspace uuid, p_pipeline uuid,
  p_stage uuid default null, p_title text default null,
  p_amount numeric default null, p_company uuid default null, p_person uuid default null
) returns uuid language plpgsql security definer set search_path = public as $$
declare v_stage uuid; v_id uuid; v_title text;
begin
  if not is_workspace_member(p_workspace, p_privy) then raise exception 'NOT_A_MEMBER'; end if;

  -- A deal is a record somebody typed, and it was not counted as one.
  perform enforce_record_limit(p_workspace, 1);

  if not exists (select 1 from pipelines where id = p_pipeline and workspace_id = p_workspace) then
    raise exception 'PIPELINE_NOT_FOUND';
  end if;

  -- A stage from another pipeline would put the card in a column nobody can see.
  v_stage := (select s.id from pipeline_stages s
               where s.id = p_stage and s.pipeline_id = p_pipeline);
  if v_stage is null then
    v_stage := (select s.id from pipeline_stages s
                 where s.pipeline_id = p_pipeline order by s.position limit 1);
  end if;
  if v_stage is null then raise exception 'PIPELINE_HAS_NO_STAGES'; end if;

  if p_company is not null
     and not exists (select 1 from organizations o where o.id = p_company and o.workspace_id = p_workspace) then
    raise exception 'COMPANY_NOT_FOUND';
  end if;
  if p_person is not null
     and not exists (select 1 from people pe where pe.id = p_person and pe.workspace_id = p_workspace) then
    raise exception 'PERSON_NOT_FOUND';
  end if;

  v_title := nullif(btrim(coalesce(p_title, '')), '');
  if v_title is null and p_company is null and p_person is null then
    raise exception 'NEEDS_A_SUBJECT: give it a name, a company or a person';
  end if;

  insert into pipeline_records (workspace_id, pipeline_id, stage_id, person_id, company_id,
                                title, amount, status, position)
  values (p_workspace, p_pipeline, v_stage, p_person, p_company,
          v_title, p_amount,
          coalesce((select case when s.stage_type = 'open' then 'active' else s.stage_type end
                    from pipeline_stages s where s.id = v_stage), 'active'),
          -- New cards go to the TOP of their column. Appending puts the thing
          -- you just typed below everything you have not looked at in a month.
          coalesce((select min(r.position) from pipeline_records r
                     where r.pipeline_id = p_pipeline and r.stage_id = v_stage), 0) - 1)
  returning id into v_id;

  return v_id;
end $$;


-- ── Orders (0124), also free ────────────────────────────────────────────────
create or replace function save_order(p_privy text, p_workspace uuid, p_id uuid, p_data jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_status text; v_was_applied boolean := false; it jsonb; n int := 0;
begin
  if not is_workspace_member(p_workspace, p_privy) then raise exception 'NOT_A_MEMBER'; end if;
  v_status := coalesce(nullif(p_data->>'status',''), 'draft');
  if not order_holds_stock(v_status)
     and v_status not in ('draft','pending','cancelled','refunded') then
    raise exception 'INVALID_STATUS';
  end if;

  -- Only on CREATE. Editing an order somebody already has must never be
  -- refused for being over a limit — that would strand rows a workspace is
  -- already holding, uneditable, which is a worse product than one that let
  -- them in.
  if p_id is null then
    perform enforce_record_limit(p_workspace, 1);
    insert into orders (workspace_id, number, organization_id, person_id, status, currency,
                        placed_at, ship_to, notes)
    values (p_workspace, nullif(p_data->>'number',''),
            -- Both ids are re-checked against the workspace, as
            -- create_pipeline_record does: neither column is trusted from the
            -- client, and a foreign id would render as a blank customer forever.
            (select o.id from organizations o where o.id = nullif(p_data->>'organization_id','')::uuid and o.workspace_id = p_workspace),
            (select pe.id from people pe where pe.id = nullif(p_data->>'person_id','')::uuid and pe.workspace_id = p_workspace),
            v_status, coalesce(nullif(p_data->>'currency',''), 'USD'),
            nullif(p_data->>'placed_at','')::date, nullif(p_data->>'ship_to',''), nullif(p_data->>'notes',''))
    returning id into v_id;
  else
    select stock_applied into v_was_applied from orders where id = p_id and workspace_id = p_workspace;
    if v_was_applied is null then raise exception 'NOT_FOUND'; end if;
    -- Give the stock back before the lines change underneath it.
    if v_was_applied then perform apply_order_stock(p_id, false); end if;

    update orders set
      number          = case when p_data ? 'number' then nullif(p_data->>'number','') else number end,
      organization_id = case when p_data ? 'organization_id'
                             then (select o.id from organizations o where o.id = nullif(p_data->>'organization_id','')::uuid and o.workspace_id = p_workspace)
                             else organization_id end,
      person_id       = case when p_data ? 'person_id'
                             then (select pe.id from people pe where pe.id = nullif(p_data->>'person_id','')::uuid and pe.workspace_id = p_workspace)
                             else person_id end,
      status          = case when p_data ? 'status' then v_status else status end,
      currency        = case when p_data ? 'currency' then coalesce(nullif(p_data->>'currency',''), currency) else currency end,
      placed_at       = case when p_data ? 'placed_at' then nullif(p_data->>'placed_at','')::date else placed_at end,
      ship_to         = case when p_data ? 'ship_to' then nullif(p_data->>'ship_to','') else ship_to end,
      notes           = case when p_data ? 'notes' then nullif(p_data->>'notes','') else notes end
     where id = p_id and workspace_id = p_workspace returning id into v_id;
  end if;

  -- Items only when the key is PRESENT, so a status-only update does not wipe
  -- the lines. 0088's rule, applied to a child collection.
  if p_data ? 'items' then
    delete from order_items where order_id = v_id;
    for it in select * from jsonb_array_elements(coalesce(p_data->'items', '[]'::jsonb)) loop
      insert into order_items (order_id, product_id, name, sku, quantity, unit_price, position)
      select v_id,
             pr.id,
             -- Snapshot: the product's name today, kept forever. Falls back to
             -- whatever the client sent when the line is not a catalogue item.
             coalesce(pr.name, nullif(it->>'name',''), 'Item'),
             coalesce(pr.sku, nullif(it->>'sku','')),
             coalesce(nullif(it->>'quantity','')::numeric, 1),
             -- An explicit price wins, so a discount survives; otherwise the
             -- catalogue price at the moment of the order.
             coalesce(nullif(it->>'unit_price','')::numeric, pr.unit_price, 0),
             n
        from (select 1) _
        left join products pr on pr.id = nullif(it->>'product_id','')::uuid
                             and pr.workspace_id = p_workspace;
      n := n + 1;
    end loop;
  end if;

  -- Re-apply if this order's status still holds stock.
  select status into v_status from orders where id = v_id;
  if order_holds_stock(v_status) then perform apply_order_stock(v_id, true); end if;
  return v_id;
end $$;

/**
 * Move an order along, and move the stock with it.
 *
 * The only place a status change has a stock consequence, so the two can never
 * be done separately and disagree.
 */

-- ── Automations (0037): Free includes 0, Team 20, and nothing checked ───────
-- The limit that most clearly maps to money. `automations` is also a gated
-- FEATURE, but feature gating lives in lib/plans-server.ts and covers the
-- routes it was wired into — the browser reaches this function through
-- /api/rpc, which does not consult it. A count of zero and a feature flag of
-- false are the same fact said twice, and only one of them was being read.
create or replace function save_automation(p_privy text, p_workspace uuid, p_id uuid, p_data jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_tt text := coalesce(nullif(p_data->>'trigger_type',''),'event');
begin
  if not is_workspace_member(p_workspace, p_privy) then raise exception 'NOT_A_MEMBER'; end if;
  if p_id is null then
    -- Create only. An existing automation stays editable and switchable off
    -- whatever the plan says, because the alternative is a workspace that
    -- downgraded being unable to turn off the thing still running.
    perform enforce_plan_limit(p_workspace, 'automations',
      (select count(*) from automations where workspace_id = p_workspace), 1);

    insert into automations (workspace_id, owner_privy, name, enabled, trigger_type, object, event, conditions, actions, schedule, webhook_token)
    values (p_workspace, p_privy, coalesce(nullif(p_data->>'name',''),'Untitled automation'),
            coalesce((p_data->>'enabled')::boolean, true), v_tt,
            coalesce(nullif(p_data->>'object',''),'companies'), coalesce(nullif(p_data->>'event',''),'created'),
            coalesce(p_data->'conditions','[]'::jsonb), coalesce(p_data->'actions','[]'::jsonb),
            case when v_tt = 'schedule' then p_data->'schedule' else null end,
            case when v_tt = 'webhook' then 'hook_' || replace(gen_random_uuid()::text, '-', '') else null end)
    returning id into v_id;
  else
    update automations set
      name = coalesce(nullif(p_data->>'name',''), name),
      enabled = coalesce((p_data->>'enabled')::boolean, enabled),
      trigger_type = v_tt,
      object = coalesce(nullif(p_data->>'object',''), object),
      event = coalesce(nullif(p_data->>'event',''), event),
      conditions = coalesce(p_data->'conditions', conditions),
      actions = coalesce(p_data->'actions', actions),
      schedule = case when v_tt = 'schedule' then p_data->'schedule' else null end,
      webhook_token = case when v_tt = 'webhook' then coalesce(webhook_token, 'hook_' || replace(gen_random_uuid()::text, '-', '')) else null end
    where id = p_id and workspace_id = p_workspace
    returning id into v_id;
  end if;
  return v_id;
end $$;

-- ── Open positions (0094) ───────────────────────────────────────────────────
create or replace function hr_save_position(p_privy text, p_id uuid, p_data jsonb, p_assessment jsonb default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_c uuid; v_member uuid; v_id uuid; v_title text;
begin
  v_c := hr_company_id(p_privy);
  if v_c is null then raise exception 'NO_COMPANY: your account is not linked to a company'; end if;

  v_title := nullif(btrim(coalesce(p_data->>'title', '')), '');

  if p_id is null then
    if v_title is null then raise exception 'TITLE_REQUIRED'; end if;
    -- Free includes one open role, Team ten. Counted against the HR company,
    -- which IS the workspace id (0005's sync trigger).
    perform enforce_plan_limit(v_c, 'positions',
      (select count(*) from positions where company_id = v_c), 1);

    -- created_by references company_users(id) and is nullable; a workspace
    -- member with no legacy ATS row still gets to create a position rather
    -- than being blocked by a row they never knew existed.
    select cu.id into v_member
    from company_users cu
    where cu.privy_user_id = p_privy and cu.company_id = v_c
    order by cu.created_at asc limit 1;

    insert into positions (company_id, title, description, department, location,
                           employment_type, neuro_profile, is_active, is_published, created_by)
    values (v_c, v_title,
            nullif(p_data->>'description', ''),
            nullif(p_data->>'department', ''),
            nullif(p_data->>'location', ''),
            nullif(p_data->>'employment_type', ''),
            nullif(p_data->>'neuro_profile', ''),
            coalesce((p_data->>'is_active')::boolean, true),
            coalesce((p_data->>'is_published')::boolean, true),
            v_member)
    returning id into v_id;

    -- The default assessment is created HERE, in the same transaction, because
    -- assessment_templates is in 0077's revoke list too and the client can no
    -- longer insert it. Atomicity is the bonus: the old two-step could leave a
    -- position with no assessment, which breaks the candidate flow silently —
    -- the client even had a comment apologising for that state.
    if p_assessment is not null and jsonb_typeof(p_assessment->'questions') = 'array' then
      insert into assessment_templates (company_id, position_id, name, description, questions, is_default)
      values (v_c, v_id,
              coalesce(nullif(p_assessment->>'name', ''), v_title || ' Assessment'),
              nullif(p_assessment->>'description', ''),
              p_assessment->'questions', true);
    end if;
  else
    update positions p set
      title            = case when p_data ? 'title'           then coalesce(v_title, p.title) else p.title end,
      description      = case when p_data ? 'description'     then nullif(p_data->>'description', '') else p.description end,
      department       = case when p_data ? 'department'      then nullif(p_data->>'department', '') else p.department end,
      location         = case when p_data ? 'location'        then nullif(p_data->>'location', '') else p.location end,
      employment_type  = case when p_data ? 'employment_type' then nullif(p_data->>'employment_type', '') else p.employment_type end,
      neuro_profile    = case when p_data ? 'neuro_profile'   then nullif(p_data->>'neuro_profile', '') else p.neuro_profile end,
      is_active        = case when p_data ? 'is_active'       then (p_data->>'is_active')::boolean else p.is_active end,
      is_published     = case when p_data ? 'is_published'    then (p_data->>'is_published')::boolean else p.is_published end,
      updated_at       = now()
    where p.id = p_id and p.company_id = v_c
    returning p.id into v_id;

    if v_id is null then raise exception 'NOT_FOUND'; end if;
  end if;

  return hr_get_position(p_privy, v_id);
end $$;

-- The grants each of these already had. Repeated because `create or replace`
-- keeps existing grants but a function that was DROPPED and recreated would not
-- — and because PUBLIC gets EXECUTE by default on anything Postgres creates,
-- which is the hole 0046 opened and 0105 swept.
revoke all on function create_pipeline_record(text, uuid, uuid, uuid, text, numeric, uuid, uuid) from public, anon, authenticated;
revoke all on function save_order(text, uuid, uuid, jsonb)                                       from public, anon, authenticated;
revoke all on function save_automation(text, uuid, uuid, jsonb)                                  from public, anon, authenticated;
revoke all on function hr_save_position(text, uuid, jsonb, jsonb)                                from public, anon, authenticated;
grant execute on function create_pipeline_record(text, uuid, uuid, uuid, text, numeric, uuid, uuid) to service_role;
grant execute on function save_order(text, uuid, uuid, jsonb)                                       to service_role;
grant execute on function save_automation(text, uuid, uuid, jsonb)                                  to service_role;
grant execute on function hr_save_position(text, uuid, jsonb, jsonb)                                to service_role;

notify pgrst, 'reload schema';
